### ISSUE TITLE
Error resolving prediction

### ISSUE THREAD

**Issue by RakSrinaNa** [RakSrinaNa/ChannelPointsMiner#270]
### Description

Seems like `returnRatioForWin` can be infinite.

https://github.com/RakSrinaNa/ChannelPointsMiner/blob/develop/miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/BaseDatabase.java#L248

Calculation is made here: https://github.com/RakSrinaNa/ChannelPointsMiner/blob/2334cfbc5146042d808a076eb915b20c00598175/miner/src/main/java/fr/raksrinana/channelpointsminer/miner/database/DatabaseEventHandler.java#L67

So infinite probably happens when a prediction is completed with 0 points spent on the given outcome (no predictors). In this case return ratio is unknown and should probably be set to null.

### Version / commit

2334cfbc5146042d808a076eb915b20c00598175

### Relevant log output

```shell
java.sql.SQLSyntaxErrorException: (conn=49897) Unknown column 'Infinity' in 'field list'
        at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:280) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:368) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:137) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:833) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:772) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:691) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:634) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:95) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:334) ~[mariadb-java-client-3.0.7.jar:?]
        at org.mariadb.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:311) ~[mariadb-java-client-3.0.7.jar:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-5.0.1.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:?]
        at fr.raksrinana.channelpointsminer.miner.database.BaseDatabase.resolvePrediction(BaseDatabase.java:248) ~[classes/:?]
        at fr.raksrinana.channelpointsminer.miner.database.DatabaseEventHandler.onEventUpdatedEvent(DatabaseEventHandler.java:68) ~[classes/:?]
        at fr.raksrinana.channelpointsminer.miner.event.EventHandlerAdapter.onEvent(EventHandlerAdapter.java:82) ~[classes/:?]
        at fr.raksrinana.channelpointsminer.miner.miner.Miner.lambda$onEvent$1(Miner.java:325) ~[classes/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by RakSrinaNa** [comment]
Doesn't make sense to return null. Instead we'll return a fixed value. Technically it is infinity. We could go for Double.MAX_VALUE but it doesn't make sense to me. Instead we'll go for 100_000 which will indicate it is a "huge" ROI.
