### ISSUE TITLE
Logging in with 2FA shows HTTP 400 "client blocked from this operation"

### ISSUE THREAD

**Issue by atraholt** [RakSrinaNa/ChannelPointsMiner#307]
### Description

When running the Docker container (both tag latest and develop) I get an error about HTTP 400. See log. Is this a misconfig on my side? 

### Version / commit

867c41823ad92c6ccb806dafddc0d41435af482b

### Relevant log output

```shell
Enter 2FA token for user HIDDEN_USERNAME:
999999
14:57:04,219 DEBUG [main] f.r.c.m.a.p.PassportApi {account_name=HIDDEN_USERNAME} - Sending passport login request
14:57:04,834 TRACE [main] f.r.c.m.l.UnirestLogger {account_name=HIDDEN_USERNAME} - Sending request to https://passport.twitch.tv/login
14:57:06,021 ERROR [main] f.r.c.m.l.UnirestLogger {account_name=HIDDEN_USERNAME} - Failed to request https://passport.twitch.tv/login got statusCode `400` and parsing error: Optional.empty
Exception in thread "main" java.lang.IllegalStateException: Failed to login
        at fr.raksrinana.channelpointsminer.miner.miner.Miner.login(Miner.java:168)
        at fr.raksrinana.channelpointsminer.miner.miner.Miner.start(Miner.java:128)
        at fr.raksrinana.channelpointsminer.miner.MinerApplication.main(MinerApplication.java:49)
Caused by: fr.raksrinana.channelpointsminer.miner.api.passport.exceptions.LoginException: Failed to login (400)[5027]: client blocked from this operation
        at fr.raksrinana.channelpointsminer.miner.api.passport.PassportApi.login(PassportApi.java:155)
        at fr.raksrinana.channelpointsminer.miner.api.passport.PassportApi.twoFactorLogin(PassportApi.java:115)
        at fr.raksrinana.channelpointsminer.miner.api.passport.PassportApi.login(PassportApi.java:71)
        at fr.raksrinana.channelpointsminer.miner.miner.Miner.login(Miner.java:158)
        ... 2 more
```

**Comment by atraholt** [comment]
Built a copy of the locally running Java version as well, same error.
